sudo: false
dist: trusty

language: python
python:
    - "3.6"
cache: pip

env: 
    - TEST_ENV=travis

services: 
    - postgresql

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -q -U postgres -d travis_ci_test -f ./src/test/sql/schema/test_chado_schema.sql

script:
    - for f in src/test/sql/data/*.sql ; do psql -q -U postgres -d travis_ci_test -f $f ; done
    - pytest src/test/test_testdb_loaded/test_testdb_prep_successful.py
    - python src/app.py -c src/test/credentials/travis.cfg -d src/test/proformae -l production -v