FROM flybase/harvdev-docker:alpine_3.10.2

WORKDIR /usr/src/app

COPY requirements-test.txt .

RUN pip install -r requirements-test.txt

COPY . .

RUN cd /usr/src/app/harvdev-utils && \
    python3 setup.py install

CMD ["python3", "-u", "src/app.py"]
