FROM python:3.6.3-alpine3.6

RUN apk add --no-cache \
    postgresql-dev \
    gcc \ 
    python3-dev \
    musl-dev \
    git

WORKDIR /usr/src/app

ADD . .

RUN pip install -r requirements-test.txt

RUN cd /usr/src/app/harvdev-utils && \
    python3 setup.py install


CMD ["python3", "-u", "src/app.py"]