version: '3.2'

services:
  kea:
    build: .
    network_mode: "host"
    container_name: kea
    volumes:
      - type: bind
        source: ./src/test_data
        target: /usr/src/app/data
        read_only: true
