from model.tables.analysi import Analysi
from model.tables.analysisfeature import Analysisfeature
from model.tables.analysisgrp import Analysisgrp
from model.tables.analysisgrpmember import Analysisgrpmember
from model.tables.analysisprop import Analysisprop
from model.tables.cellline import CellLine
from model.tables.celllinecvterm import CellLineCvterm
from model.tables.celllinecvtermprop import CellLineCvtermprop
from model.tables.celllinedbxref import CellLineDbxref
from model.tables.celllinefeature import CellLineFeature
from model.tables.celllinelibrary import CellLineLibrary
from model.tables.celllinelibraryprop import CellLineLibraryprop
from model.tables.celllinepub import CellLinePub
from model.tables.celllinerelationship import CellLineRelationship
from model.tables.celllinestrain import CellLineStrain
from model.tables.celllinestrainprop import CellLineStrainprop
from model.tables.celllinesynonym import CellLineSynonym
from model.tables.celllineprop import CellLineprop
from model.tables.celllineproppub import CellLinepropPub
from model.tables.contact import Contact
from model.tables.cv import Cv
from model.tables.cvterm import Cvterm
from model.tables.cvtermdbxref import CvtermDbxref
from model.tables.cvtermrelationship import CvtermRelationship
from model.tables.cvtermpath import Cvtermpath
from model.tables.cvtermprop import Cvtermprop
from model.tables.cvtermsynonym import Cvtermsynonym
from model.tables.db import Db
from model.tables.dbxref import Dbxref
from model.tables.dbxrefprop import Dbxrefprop
from model.tables.eimage import Eimage
from model.tables.environment import Environment
from model.tables.environmentcvterm import EnvironmentCvterm
from model.tables.expression import Expression
from model.tables.expressioncvterm import ExpressionCvterm
from model.tables.expressioncvtermprop import ExpressionCvtermprop
from model.tables.expressionimage import ExpressionImage
from model.tables.expressionpub import ExpressionPub
from model.tables.expressionprop import Expressionprop
from model.tables.feature import Feature
from model.tables.featurecvterm import FeatureCvterm
from model.tables.featurecvtermdbxref import FeatureCvtermDbxref
from model.tables.featurecvtermprop import FeatureCvtermprop
from model.tables.featuredbxref import FeatureDbxref
from model.tables.featureexpression import FeatureExpression
from model.tables.featureexpressionprop import FeatureExpressionprop
from model.tables.featuregenotype import FeatureGenotype
from model.tables.featuregrpmember import FeatureGrpmember
from model.tables.featuregrpmemberpub import FeatureGrpmemberPub
from model.tables.featurehumanhealthdbxref import FeatureHumanhealthDbxref
from model.tables.featureinteraction import FeatureInteraction
from model.tables.featureinteractionpub import FeatureInteractionPub
from model.tables.featureinteractionprop import FeatureInteractionprop
from model.tables.featurephenotype import FeaturePhenotype
from model.tables.featurepub import FeaturePub
from model.tables.featurepubprop import FeaturePubprop
from model.tables.featurerelationship import FeatureRelationship
from model.tables.featurerelationshippub import FeatureRelationshipPub
from model.tables.featurerelationshipprop import FeatureRelationshipprop
from model.tables.featurerelationshipproppub import FeatureRelationshippropPub
from model.tables.featuresynonym import FeatureSynonym
from model.tables.featureloc import Featureloc
from model.tables.featurelocpub import FeaturelocPub
from model.tables.featuremap import Featuremap
from model.tables.featuremappub import FeaturemapPub
from model.tables.featurepo import Featurepo
from model.tables.featureprop import Featureprop
from model.tables.featureproppub import FeaturepropPub
from model.tables.featurerange import Featurerange
from model.tables.genotype import Genotype
from model.tables.grp import Grp
from model.tables.grpcvterm import GrpCvterm
from model.tables.grpdbxref import GrpDbxref
from model.tables.grppub import GrpPub
from model.tables.grppubprop import GrpPubprop
from model.tables.grprelationship import GrpRelationship
from model.tables.grprelationshippub import GrpRelationshipPub
from model.tables.grprelationshipprop import GrpRelationshipprop
from model.tables.grpsynonym import GrpSynonym
from model.tables.grpmember import Grpmember
from model.tables.grpmembercvterm import GrpmemberCvterm
from model.tables.grpmemberpub import GrpmemberPub
from model.tables.grpmemberprop import Grpmemberprop
from model.tables.grpmemberproppub import GrpmemberpropPub
from model.tables.grpprop import Grpprop
from model.tables.grpproppub import GrppropPub
from model.tables.humanhealth import Humanhealth
from model.tables.humanhealthcvterm import HumanhealthCvterm
from model.tables.humanhealthcvtermprop import HumanhealthCvtermprop
from model.tables.humanhealthdbxref import HumanhealthDbxref
from model.tables.humanhealthdbxrefprop import HumanhealthDbxrefprop
from model.tables.humanhealthdbxrefproppub import HumanhealthDbxrefpropPub
from model.tables.humanhealthfeature import HumanhealthFeature
from model.tables.humanhealthfeatureprop import HumanhealthFeatureprop
from model.tables.humanhealthphenotype import HumanhealthPhenotype
from model.tables.humanhealthphenotypeprop import HumanhealthPhenotypeprop
from model.tables.humanhealthpub import HumanhealthPub
from model.tables.humanhealthpubprop import HumanhealthPubprop
from model.tables.humanhealthrelationship import HumanhealthRelationship
from model.tables.humanhealthrelationshippub import HumanhealthRelationshipPub
from model.tables.humanhealthsynonym import HumanhealthSynonym
from model.tables.humanhealthprop import Humanhealthprop
from model.tables.humanhealthproppub import HumanhealthpropPub
from model.tables.interaction import Interaction
from model.tables.interactioncellline import InteractionCellLine
from model.tables.interactioncvterm import InteractionCvterm
from model.tables.interactioncvtermprop import InteractionCvtermprop
from model.tables.interactionexpression import InteractionExpression
from model.tables.interactionexpressionprop import InteractionExpressionprop
from model.tables.interactiongroup import InteractionGroup
from model.tables.interactiongroupfeatureinteraction import InteractionGroupFeatureInteraction
from model.tables.interactionpub import InteractionPub
from model.tables.interactionprop import Interactionprop
from model.tables.interactionproppub import InteractionpropPub
from model.tables.library import Library
from model.tables.librarycvterm import LibraryCvterm
from model.tables.librarycvtermprop import LibraryCvtermprop
from model.tables.librarydbxref import LibraryDbxref
from model.tables.librarydbxrefprop import LibraryDbxrefprop
from model.tables.libraryexpression import LibraryExpression
from model.tables.libraryexpressionprop import LibraryExpressionprop
from model.tables.libraryfeature import LibraryFeature
from model.tables.libraryfeatureprop import LibraryFeatureprop
from model.tables.librarygrpmember import LibraryGrpmember
from model.tables.libraryhumanhealth import LibraryHumanhealth
from model.tables.libraryhumanhealthprop import LibraryHumanhealthprop
from model.tables.libraryinteraction import LibraryInteraction
from model.tables.librarypub import LibraryPub
from model.tables.libraryrelationship import LibraryRelationship
from model.tables.libraryrelationshippub import LibraryRelationshipPub
from model.tables.librarystrain import LibraryStrain
from model.tables.librarystrainprop import LibraryStrainprop
from model.tables.librarysynonym import LibrarySynonym
from model.tables.libraryprop import Libraryprop
from model.tables.libraryproppub import LibrarypropPub
from model.tables.lock import Lock
from model.tables.organism import Organism
from model.tables.organismcvterm import OrganismCvterm
from model.tables.organismcvtermprop import OrganismCvtermprop
from model.tables.organismdbxref import OrganismDbxref
from model.tables.organismgrpmember import OrganismGrpmember
from model.tables.organismlibrary import OrganismLibrary
from model.tables.organismpub import OrganismPub
from model.tables.organismprop import Organismprop
from model.tables.organismproppub import OrganismpropPub
from model.tables.phendesc import Phendesc
from model.tables.phenotype import Phenotype
from model.tables.phenotypecomparison import PhenotypeComparison
from model.tables.phenotypecomparisoncvterm import PhenotypeComparisonCvterm
from model.tables.phenotypecvterm import PhenotypeCvterm
from model.tables.phenstatement import Phenstatement
from model.tables.project import Project
from model.tables.pub import Pub
from model.tables.pubdbxref import PubDbxref
from model.tables.pubrelationship import PubRelationship
from model.tables.pubauthor import Pubauthor
from model.tables.pubprop import Pubprop
from model.tables.strain import Strain
from model.tables.straincvterm import StrainCvterm
from model.tables.straincvtermprop import StrainCvtermprop
from model.tables.straindbxref import StrainDbxref
from model.tables.strainfeature import StrainFeature
from model.tables.strainfeatureprop import StrainFeatureprop
from model.tables.strainphenotype import StrainPhenotype
from model.tables.strainphenotypeprop import StrainPhenotypeprop
from model.tables.strainpub import StrainPub
from model.tables.strainrelationship import StrainRelationship
from model.tables.strainrelationshippub import StrainRelationshipPub
from model.tables.strainsynonym import StrainSynonym
from model.tables.strainprop import Strainprop
from model.tables.strainproppub import StrainpropPub
from model.tables.synonym import Synonym
from model.tables.tableinfo import Tableinfo
